id: onc.ig
canonical: http://open-nursing-core.org
name: OpenNursingCoreIG
title: Open Nursing Core FHIR Implementation Guide (ONC-IG)
status: draft
version: 0.1.0
fhirVersion: 4.0.1
publisher: "The Open Nursing Community"
description: "Foundational FHIR profiles for the nursing process (ADPIE)."
license: MIT
copyrightYear: 2025+
releaseLabel: ci-build
dependencies:
  fhir.r4.ukcore: 1.0.0
