id: onc.ig
canonical: https://clinyqai.github.io/open-nursing-core-ig
name: OpenNursingCoreIG
title: Open Nursing Core FHIR Implementation Guide
status: active
version: 1.0.0
fhirVersion: 4.0.1
publisher: "The Open Nursing Community"
description: "Foundational FHIR profiles for the nursing process (ADPIE), inspired by MCINDS principles."
license: MIT
copyrightYear: 2025+
releaseLabel: ci-build
FSHOnly: false
